export const environment = {
  production: false,
  title: 'App-DCT | Local',
  apiURL: 'http://localhost:5000/api',
  adminRegistrationAPI: 'http://localhost:5000/api/admin',
  doctorRegistrationAPI: 'http://localhost:5000/api/doctor',
  adminLogin: 'http://localhost:5000/api/admin/login',
  doctorRegistration: 'http://localhost:4200/doctorregistration',
  patientRegistrationAPI: 'http://localhost:5000/api/patient/create',
  patientRegistration: 'http://localhost:4200/patientregistration',
  login: 'http://localhost:5000/api/login',
  forgot: 'http://localhost:5000/api/forgot',
  doctorLogin: 'http://localhost:4200/doctorlogin',
  doctorHomepage: 'http://localhost:4200/doctorhomepage',
  recaptcha: {
    siteKey: '6LdfWRYgAAAAAO64AMfigSwfKz5-5uxZrNGiBVBK',
  },
  patientlist: 'http://localhost:4200/patientlist',
  servicesAdd: 'http://localhost:5000/api/services/add',
  servicesGet: 'http://localhost:5000/api/services/get',
  labtestAdd: 'http://localhost:5000/api/labtest/add',
  labtestGet: 'http://localhost:5000/api/labtest/get',
};